### PR TITLE
allow multiple non-adjacent hyphens

### PR DESCRIPTION
**Pull request by chrispruitt**
This PR fixes the issue described here -> https://github.com/outsideris/citizen/issues/63

### CODE REVIEW

**Comment by chrispruitt** [comment]
any chance we could get this merged in? Thanks!

**Comment by FalcoSuessgott** [comment]
Need this feature :)

**Comment by justmiles** [comment]
Looks good to me! Can we get this merged?

**Comment by chrispruitt** [comment]
Any update on this by chance?

**Pull request merged**
