### PR TITLE
Google Bucket support + Helm chart

### PR DESCRIPTION
**Pull request by halradaideh**
As explained in the title, I did the following:

- Add a helm chart for Kubernetes support
- the chart contains mongo as a standalone from Bitnami
- add Google Bucket support into the citizen app
- some tweaking for the docker and adding entrypoint
- add a logic to read modules from repos and push changes into the citizen server

it needs a lot of review and adding test cases for the google implementation (first time in my life write JS)

it is working on my env (tested)

### CODE REVIEW

**Comment by grizzls** [comment]
We're interested in GCS Storage support. Any idea when this will get merged?

**Comment by lexfrei** [comment]
Any news on this?
cc @outsideris

**Comment by lexfrei** [comment]
@halradaideh can you update this PR, please? As I can see there are some conflicts.

**Comment by outsideris** [comment]
Sorry for the late response. 
I'm not familiar with GCP, so I need to prepare a test environment for GCP. 
The current code base is far from when this PR was created. I need to rebase it and merge it on my side after testing it on GCP.

**Comment by halradaideh** [comment]
i'll rebase it and try to use your latest code as i use citizen on production right now
will get back here on Sunday if I remembered

**Comment by halradaideh** [comment]
i pushed a new branch mergable with the latets code, did not test it tho
@outsideris

**Pull request closed without merging**
